name: Deploy to EC2

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "wizard#778" | docker login -u "sahib64" --password-stdin

      - name: Build backend image
        run: |
          docker build -t "sahib64"/workboard-api:latest ./WorkBoard_Backend

      - name: Push backend image
        run: |
          docker push "sahib64"/workboard-api:latest

      - name: Build frontend image
        run: |
          docker build -t "sahib64"/workboard-frontend:latest ./WorkBoard_Frontend

      - name: Push frontend image
        run: |
          docker push "sahib64"/workboard-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/workboard-app

            docker compose pull

            docker compose up -d
